export default {
    name: 'vCompraPedidoItems',
    title: 'Artículos pedidos',
    apiPath: 'socio_pedido_items',

    headerActions: [
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'socio_pedido1.fecha',
            title: 'Fecha',
            prop: 'socio_pedido1.fecha',
            type: 'date',
            format: 'date',
            width: '8rem',
            show: true,
            sort: true,
            orden: 1,
        },
        {
            id: 'socio_pedido1.codigo',
            title: 'Nro pedido',
            prop: 'socio_pedido1.codigo',
            type: 'text',
            width: '11rem',
            show: true,
            seek: true,
            sort: true,
            orden: 2,
        },
        {
            id: 'socio_pedido1.socio1.nombres',
            title: 'Proveedor',
            prop: 'socio_pedido1.socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            width: '15rem',
            show: true,
            seek: true,
            sort: true,
            orden: 3,
        },
        {
            id: 'articulo1.nombre',
            title: 'Artículo',
            type: 'text',
            prop: 'articulo1.nombre',
            width: '20rem',
            show: true,
            seek: true,
            sort: true,
            orden: 4,
        },
        {
            id: 'pu',
            title: 'Valor unitario',
            type: 'number',
            toRight: true,
            width: '8rem',
            show: true,
            sort: true,
            orden: 5,
        },
        {
            id: 'cantidad',
            title: 'Cantidad',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
            sort: true,
            orden: 6,
        },
        {
            id: 'entregado',
            title: 'Entregado',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
            sort: true,
            orden: 7,
        },
    ],
}
