export default {
    name: 'vColaboradores',
    title: 'Colaboradores',
    apiPath: 'colaboradores',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vColaboradores:crear',
        },
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'id',
            title: 'id',
            type: 'text',
            width: '5rem',
            show: false,
            orden: 1,
        },
        {
            id: 'nombres',
            title: 'Nombres y apellidos',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'doc_tipo',
            title: 'Tipo de documento',
            prop: 'doc_tipo1.nombre',
            type: 'select',
            systemKey: 'documentos_identidad',
            width: '10rem',
            show: true,
            orden: 3,
        },
        {
            id: 'doc_numero',
            title: 'Número de documento',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'fecha_nacimiento',
            title: 'Fecha de nacimiento',
            type: 'date',
            width: '8rem',
            show: true,
            orden: 5,
        },
        {
            id: 'sexo',
            title: 'Sexo',
            prop: 'sexo1.nombre',
            type: 'select',
            systemKey: 'generos',
            width: '8rem',
            show: true,
            orden: 6,
        },
        {
            id: 'correo',
            title: 'Email',
            type: 'text',
            width: '10rem',
            show: true,
            orden: 7,
        },
        {
            id: 'telefono',
            title: 'Teléfono',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 8,
        },
        {
            id: 'direccion',
            title: 'Dirección',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 9,
        },
        {
            id: 'cargo',
            title: 'Cargo',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 10,
        },
        {
            id: 'activo',
            title: 'Activo?',
            prop: 'activo1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'yesno',
            width: '5rem',
            show: true,
            orden: 11,
        },
        {
            id: 'has_signin',
            title: 'Tiene usuario?',
            prop: 'has_signin1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'yesno',
            width: '5rem',
            show: true,
            orden: 12,
        },
    ],

    tableRowActions: [
        {
            label: 'Ver',
            icon: 'fa-regular fa-folder-open',
            action: 'ver',
            permiso: 'vColaboradores:ver',
        },
        {
            label: 'Editar',
            icon: 'fa-solid fa-pen-to-square',
            action: 'editar',
            permiso: 'vColaboradores:editar',
        },
        {
            label: 'Eliminar',
            icon: 'fa-solid fa-trash-can',
            action: 'vista.eliminar',
            permiso: 'vColaboradores:eliminar',
        },
    ],
}
