export const columns = [
    {
        id: 'nombres',
        title: 'Nombres y apellidos',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'doc_tipo',
        title: 'Tipo de documento',
        prop: 'doc_tipo1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'doc_numero',
        title: 'Número de documento',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'fecha_nacimiento',
        title: 'Fecha de nacimiento',
        type: 'date',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'sexo',
        title: 'Sexo',
        prop: 'sexo1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'correo',
        title: 'Email',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'telefono',
        title: 'Teléfono',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'direccion',
        title: 'Dirección',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'cargo',
        title: 'Cargo',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'activo',
        title: 'Activo?',
        prop: 'activo1.nombre',
        type: 'select',
        format: 'yesno',
        width: '5rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'has_signin',
        title: 'Tiene usuario?',
        prop: 'has_signin1.nombre',
        type: 'select',
        format: 'yesno',
        width: '5rem',
        show: true,
        seek: true,
        sort: true,
    },
]

export const tableRowOptions = [
    {
        label: 'Ver',
        icon: 'fa-regular fa-folder-open',
        action: 'ver',
        permiso: 'vColaboradores:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vColaboradores:editar',
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'eliminar',
        permiso: 'vColaboradores:eliminar',
    },
]
