export default {
    name: 'vArticuloCategorias',
    title: 'Categorías',
    apiPath: 'articulo_categorias',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vArticuloCategorias:crear',
        },
    ],

    tableColumns: [
        {
            id: 'categoria_nombre_completo',
            title: 'Nombre',
            type: 'text',
            width: '25rem',
            show: true,
            seek: true,
            orden: 1,
        },
        {
            id: 'activo',
            title: 'Activo?',
            prop: 'activo1.nombre',
            type: 'select',
            systemKey: 'estados',
            editable: true,
            format: 'estado',
            color: 'activo1.color',
            width: '10rem',
            show: true,
            orden: 2,
        },
        {
            id: 'is_ecommerce',
            title: 'Ecommerce?',
            prop: 'is_ecommerce1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'estado',
            color: 'is_ecommerce1.color',
            width: '10rem',
            show: true,
            orden: 3,
        },
        {
            id: 'is_destacado',
            title: 'Destacado?',
            prop: 'is_destacado1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'estado',
            color: 'is_destacado1.color',
            width: '10rem',
            show: true,
            orden: 4,
        },
        {
            id: 'descripcion',
            title: 'Descripción',
            type: 'text',
            width: '20rem',
            show: true,
            seek: true,
            orden: 5,
        },
    ],

    tableRowActions: [
        {
            label: 'Editar',
            icon: 'fa-solid fa-pen-to-square',
            action: 'editar',
            permiso: 'vArticuloCategorias:editar',
        },
        {
            label: 'Actualizar fotos',
            icon: 'fa-solid fa-image',
            action: 'openUploadFiles',
            permiso: 'vArticuloCategorias:actualizarFotos',
        },
    ],
}
