export const TABLE_COLUMNS = [
    {
        id: 'kardexes.fecha',
        title: 'Fecha',
        type: 'date',
        show: false,
    },
    {
        id: 'nombre',
        title: 'Nombre',
        type: 'text',
        width: '30rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'categoria',
        title: 'Categoría',
        prop: 'categoria1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'unidad',
        title: 'Unidad',
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'cantidad',
        title: 'Stock',
        format: 'decimal',
        toRight: true,
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'articulo_movimientos_valorizado',
        title: 'Valor',
        format: 'decimal',
        toRight: true,
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'purchase_ok',
        title: 'Se compra',
        prop: 'purchase_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
    },
    {
        id: 'sale_ok',
        title: 'Se vende',
        prop: 'sale_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
    },
    {
        id: 'produce_ok',
        title: 'Se produce',
        prop: 'produce_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
    },
]
