export const HEADER_ACTIONS = [
    {
        icon: 'fa-solid fa-download',
        text: 'Exportar página actual',
        action: 'vista.downloadActualTablePage',
        tipo: '2',
    }
]

export const TABLE_COLUMNS = [
    {
        id: 'kardexes.fecha',
        title: 'Fecha',
        type: 'date',
        show: false,
        orden: 1,
    },
    {
        id: 'nombre',
        title: 'Nombre',
        type: 'text',
        width: '30rem',
        show: true,
        seek: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'categoria',
        title: 'Categoría',
        prop: 'categoria1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'unidad',
        title: 'Unidad',
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'cantidad',
        title: 'Stock',
        format: 'decimal',
        toRight: true,
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
        orden: 5,
    },
    {
        id: 'articulo_movimientos_valorizado',
        title: 'Valor',
        format: 'decimal',
        toRight: true,
        filtrable: false,
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'purchase_ok',
        title: 'Se compra',
        prop: 'purchase_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
        orden: 7,
    },
    {
        id: 'sale_ok',
        title: 'Se vende',
        prop: 'sale_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
        orden: 8,
    },
    {
        id: 'produce_ok',
        title: 'Se produce',
        prop: 'produce_ok1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: false,
        orden: 9,
    },
]
