export const TABLE_COLUMNS = [
    {
        id: 'transaccion1.fecha',
        title: 'Fecha',
        type: 'date',
        prop: 'transaccion1.fecha',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'transaccion1.guia',
        title: 'Guía',
        type: 'text',
        prop: 'transaccion1.guia',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'transaccion1.factura',
        title: 'Factura',
        type: 'text',
        prop: 'transaccion1.factura',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'transaccion1.socio1.nombres',
        title: 'Proveedor',
        prop: 'transaccion1.socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'articulo1.nombre',
        title: 'Artículo',
        type: 'text',
        prop: 'articulo1.nombre',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'cantidad',
        title: 'Cantidad',
        type: 'number',
        format: 'decimal',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'pu',
        title: 'Valor unitario',
        type: 'number',
        format: 'decimal',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'lote',
        title: 'Lote',
        type: 'select',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'fv',
        title: 'Fecha de vencimiento',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'transaccion1.socio_pedido1.codigo',
        title: 'Nro pedido',
        prop: 'transaccion1.socio_pedido1.codigo',
        filtrable: false,
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
    },
]
