export default {
    name: 'vCompraPedidos',
    title: 'Pedidos de compra',
    apiPath: 'socio_pedidos',
    detailViewName: 'vCompraPedidoDetalle',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vCompraPedidos:crear',
        },
        {
            text: 'Recuperar',
            action: 'recuperarGuardado',
            permiso: 'vCompraPedidos:crear',
            tipo: '2',
            showIfAvance: 'mCompraPedido',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '10rem',
            show: true,
            orden: 1,
        },
        {
            id: 'codigo',
            title: 'Nro pedido',
            type: 'text',
            width: '12rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'socio',
            title: 'Proveedor',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '20rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'pago_condicion',
            title: 'Condición de pago',
            prop: 'pago_condicion1.nombre',
            type: 'select',
            systemKey: 'pago_condiciones',
            width: '12rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'moneda',
            title: 'Moneda',
            prop: 'moneda1.nombre',
            type: 'related',
            relatedUrl: 'monedas',
            width: '8rem',
            show: true,
            seek: true,
            orden: 5,
        },
        {
            id: 'monto',
            title: 'Importe',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '10rem',
            show: true,
            orden: 6,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'pedido_estados',
            format: 'estado',
            color: 'estado1.color',
            width: '10rem',
            show: true,
            orden: 7,
        },
        {
            id: 'createdBy',
            title: 'Creado por',
            prop: 'createdBy1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
            orden: 8,
        },
    ],

    tableBulkActions: [
        {
            text: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrirMasivo',
            permiso: 'vCompraPedidos:abrirCerrar',
        },
        {
            text: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrarMasivo',
            permiso: 'vCompraPedidos:abrirCerrar',
        },
    ],

    tableRowActions: [
        {
            label: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrir',
            permiso: 'vCompraPedidos:abrirCerrar',
            ocultar: { estado: 1 },
        },
        {
            label: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrar',
            permiso: 'vCompraPedidos:abrirCerrar',
            ocultar: { estado: 2 },
        },
        // {
        //     label: 'Recalcular entregados',
        //     icon: 'fa-solid fa-calculator',
        //     action: 'recalcularEntregados',
        //     permiso: 'vCompraPedidos:recalcularEntregados',
        //     ocultar: { estado: ['0', '2'] },
        // },
        // {
        //     label: 'Entregar mercadería',
        //     icon: 'fa-regular fa-circle-down',
        //     action: 'entregarMercaderia',
        //     permiso: 'vCompraPedidos:entregarMercaderia',
        //     ocultar: { estado: ['0', '2'], is_maquila: false },
        // },
        // {
        //     label: 'Ingresar mercadería',
        //     icon: 'fa-regular fa-circle-up',
        //     action: 'ingresarMercaderia',
        //     permiso: 'vCompraPedidos:ingresarMercaderia',
        //     ocultar: { estado: ['0', '2'] },
        // },
    ],
}
