export default {
    apiPath: 'socio_pedidos',
    titleKey: 'codigo',
    pathKey: 'pedido_id',
    permisoEditar: ['vCompraPedidos:editar', 'vVentaPedidos:editar'],
    permisoClonar: ['vCompraPedidos:clonar', 'vVentaPedidos:clonar'],
    permisoGuardarAvance: ['vCompraPedidos:crear', 'vVentaPedidos:crear'],

    headerActions: [
        {
            text: 'Exportar en PDF',
            icon: 'fa-regular fa-file-pdf',
            tipo: '2',
            action: 'generarPdf',
        },
        {
            text: 'Entrega',
            icon: 'fa-regular fa-truck',
            tipo: '2',
            action: 'entregar',
            permiso: 'vVentaPedidos:entregarMercaderia',
            ocultar: { tipo: 2, is_maquila: false },
        },
        {
            text: 'Recepción',
            icon: 'fa-regular fa-truck',
            tipo: '2',
            action: 'ingresar',
            permiso: 'vCompraPedidos:ingresarMercaderia',
            ocultar: { tipo: 2 },
        },
        {
            text: 'Entrega',
            icon: 'fa-regular fa-truck',
            tipo: '2',
            action: 'entregar',
            permiso: 'vVentaPedidos:entregarMercaderia',
            ocultar: { tipo: 1 },
        },
        {
            text: 'Facturas proveedor',
            icon: 'fa-solid fa-file-invoice',
            action: 'facturar',
            permiso: ['vCompraComprobantes:crear'],
            tipo: '2',
        },
        {
            text: 'Abrir',
            icon: 'fa-solid fa-check-double',
            tipo: '2',
            action: 'abrir',
            permiso: ['vCompraPedidos:abrir', 'vVentaPedidos:abrir'],
            ocultar: { estado: '1', tipo: 2 },
        },
        {
            text: 'Cerrar',
            icon: 'fa-solid fa-check-double',
            tipo: '2',
            action: 'cerrar',
            permiso: ['vCompraPedidos:cerrar', 'vVentaPedidos:cerrar'],
            ocultar: { estado: '2', tipo: 2 },
        },
    ],
}
