export default {
    apiPath: 'produccion_ordenes',
    detailPath: 'produccion_orden_id',
    detailViewName: 'vProduccionOrden',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vProduccionOrdenes:crear',
        },
        {
            text: 'Salida de insumos',
            action: 'salidaInsumosCompartidos',
            permiso: 'vProduccionOrdenes:salidaInsumosCompartidos',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '10rem',
            show: true,
        },
        {
            id: 'articulo1.nombre',
            title: 'Producto',
            prop: 'articulo1.nombre',
            type: 'related',
            relatedUrl: 'articulos',
            width: '25rem',
            show: true,
            seek: true,
        },
        {
            id: 'cantidad',
            title: 'Cantidad planificada',
            type: 'number',
            format: 'decimal',
            align: 'right',
            width: '8rem',
            show: true,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'produccion_orden_estados',
            format: 'estado',
            color: 'estado1.color',
            width: '8rem',
            show: true,
        },
        {
            id: 'productos_terminados',
            title: 'Productos terminados',
            type: 'number',
            format: 'decimal',
            filtrable: false,
            align: 'right',
            width: '8rem',
            show: true,
        },
        {
            id: 'responsable',
            title: 'Responsable',
            prop: 'responsable1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
        },
        {
            id: 'inicio',
            title: 'Hora inicio',
            prop: 'inicio1',
            width: '11rem',
            show: true,
            filtrable: false,
        },
        {
            id: 'fin',
            title: 'Hora fin',
            prop: 'fin1',
            width: '11rem',
            show: true,
            filtrable: false,
        },
        {
            id: 'linea',
            title: 'Tipo de producción',
            prop: 'linea1.nombre',
            type: 'related',
            relatedUrl: 'articulo_lineas',
            width: '10rem',
            show: true,
            seek: true,
        },
        {
            id: 'maquina',
            title: 'Máquina',
            prop: 'maquina1.nombre',
            type: 'related',
            relatedUrl: 'maquinas',
            width: '10rem',
            show: true,
            seek: true,
        },
        // {
        //     id: 'estado_calidad_revisado',
        //     title: 'Control de pesos',
        //     prop: 'estado_calidad_revisado1.nombre',
        //     format: 'estado',
        //     color: 'estado_calidad_revisado1.color',
        //     filtrable: false,
        //     width: '10rem',
        //     show: true,
        //     orden: 11,
        // },
        // {
        //     id: 'estado_cf_ppc',
        //     title: 'Control del PPC',
        //     prop: 'estado_cf_ppc1.nombre',
        //     format: 'estado',
        //     color: 'estado_cf_ppc1.color',
        //     filtrable: false,
        //     width: '10rem',
        //     show: true,
        //     orden: 12,
        // },
        {
            id: 'createdBy',
            title: 'Creado por',
            prop: 'createdBy1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
            orden: 13,
        },
    ],

    tableBulkActions: [
        {
            text: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrirMasivo',
            permiso: 'vProduccionOrdenes:abrirCerrar',
        },
        {
            text: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrarMasivo',
            permiso: 'vProduccionOrdenes:abrirCerrar',
        },
    ],

    tableRowActions: [
        {
            label: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrir',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 1 },
        },
        {
            label: 'Cerrar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrar',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 2 },
        },
        // {
        //     label: 'Productos terminados',
        //     icon: 'fa-solid fa-boxes-stacked',
        //     action: 'productosTerminados',
        //     permiso: 'vProduccionOrdenes:productosTerminados',
        // },
        // {
        //     label: 'Ver trazabilidad',
        //     icon: 'fa-solid fa-diagram-project',
        //     action: 'verTrazabilidad',
        //     permiso: 'vProduccionOrdenes:trazabilidad',
        // },
        // {
        //     label: 'Control de pesos',
        //     icon: 'fa-solid fa-star',
        //     action: 'controlPesos',
        //     permiso: 'vProduccionOrdenes:controlPesos',
        // },
        // {
        //     label: 'Control del PPC',
        //     icon: 'fa-solid fa-star',
        //     action: 'controlPpc',
        //     permiso: 'vProduccionOrdenes:controlPpc',
        // },
    ],
}
