export default {
    apiPath: 'produccion_ordenes',
    detailPath: 'produccion_orden_id',
    detailViewName: 'vProduccionOrden',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vProduccionOrdenes:crear',
        },
        {
            text: 'Salida de insumos',
            action: 'salidaInsumosCompartidos',
            permiso: 'vProduccionOrdenes:salidaInsumos',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '10rem',
            show: true,
            orden: 1,
        },
        {
            id: 'articulo',
            title: 'Producto',
            prop: 'articulo1.nombre',
            type: 'related',
            relatedUrl: 'articulos',
            width: '25rem',
            show: true,
            orden: 2,
        },
        {
            id: 'cantidad',
            title: 'Cantidad planificada',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
            orden: 3,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'produccion_orden_estados',
            format: 'estado',
            color: 'estado1.color',
            width: '8rem',
            show: true,
            orden: 4,
        },
        {
            id: 'productos_terminados',
            title: 'Productos terminados',
            type: 'number',
            format: 'decimal',
            filtrable: false,
            toRight: true,
            width: '8rem',
            show: true,
            orden: 5,
        },
        {
            id: 'linea',
            title: 'Tipo de producción',
            prop: 'linea1.nombre',
            type: 'related',
            relatedUrl: 'articulo_lineas',
            width: '10rem',
            show: true,
            seek: true,
            orden: 6,
        },
        {
            id: 'maquina',
            title: 'Máquina',
            prop: 'maquina1.nombre',
            type: 'related',
            relatedUrl: 'maquinas',
            width: '10rem',
            show: true,
            seek: true,
            orden: 7,
        },
        {
            id: 'responsable',
            title: 'Responsable',
            prop: 'responsable1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
            orden: 8,
        },
        {
            id: 'inicio',
            title: 'Hora inicio',
            format: 'datetime',
            width: '11rem',
            show: true,
            filtrable: false,
            orden: 9,
        },
        {
            id: 'fin',
            title: 'Hora fin',
            format: 'datetime',
            width: '11rem',
            show: true,
            filtrable: false,
            orden: 10,
        },
        {
            id: 'estado_calidad_revisado',
            title: 'Control de pesos',
            prop: 'estado_calidad_revisado1.nombre',
            format: 'estado',
            color: 'estado_calidad_revisado1.color',
            filtrable: false,
            width: '10rem',
            show: true,
            orden: 11,
        },
        {
            id: 'estado_cf_ppc',
            title: 'Control del PPC',
            prop: 'estado_cf_ppc1.nombre',
            format: 'estado',
            color: 'estado_cf_ppc1.color',
            filtrable: false,
            width: '10rem',
            show: true,
            orden: 12,
        },
        {
            id: 'createdBy',
            title: 'Creado por',
            prop: 'createdBy1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
            orden: 13,
        },
    ],

    tableBulkActions: [
        {
            text: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrirMasivo',
            permiso: 'vProduccionOrdenes:abrirCerrar',
        },
        {
            text: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrarMasivo',
            permiso: 'vProduccionOrdenes:abrirCerrar',
        },
    ],

    tableRowActions: [
        {
            label: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrir',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 1 },
        },
        {
            label: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrar',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 2 },
        },
        // {
        //     label: 'Ver trazabilidad',
        //     icon: 'fa-solid fa-diagram-project',
        //     action: 'verTrazabilidad',
        //     permiso: 'vProduccionOrdenes:trazabilidad',
        // },
        // {
        //     label: 'Control de pesos',
        //     icon: 'fa-solid fa-star',
        //     action: 'controlPesos',
        //     permiso: 'vProduccionOrdenes:controlPesos',
        // },
        // {
        //     label: 'Control del PPC',
        //     icon: 'fa-solid fa-star',
        //     action: 'controlPpc',
        //     permiso: 'vProduccionOrdenes:controlPpc',
        // },
    ],
}
