export default {
    name: 'vSuscripciones',
    title: 'Suscripciones',
    apiPath: 'suscripciones',

    headerActions: [],

    tableColumns: [
        {
            id: 'id',
            title: 'id',
            type: 'text',
            width: '5rem',
            show: false,
            orden: 1,
        },
        {
            id: 'plan_nombre',
            title: 'Plan',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'periodo',
            title: 'Periodo',
            type: 'text',
            width: '8rem',
            show: true,
            orden: 3,
        },
        {
            id: 'limite_usuarios',
            title: 'Usuarios',
            type: 'number',
            width: '7rem',
            show: true,
            toRight: true,
            orden: 4,
        },
        {
            id: 'precio',
            title: 'Costo',
            type: 'number',
            format: 'decimal',
            width: '7rem',
            show: true,
            toRight: true,
            orden: 5,
        },
        {
            id: 'moneda',
            title: 'Moneda',
            prop: 'moneda1.nombre',
            type: 'text',
            width: '7rem',
            show: true,
            orden: 6,
        },
        {
            id: 'fecha_inicio',
            title: 'Inicio',
            prop: 'fecha_inicio1',
            type: 'text',
            width: '9rem',
            show: true,
            orden: 7,
        },
        {
            id: 'fecha_vencimiento',
            title: 'Vencimiento',
            prop: 'fecha_vencimiento1',
            type: 'text',
            width: '9rem',
            show: true,
            orden: 8,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'suscripcion_estados',
            editable: true,
            format: 'estado',
            color: 'estado1.color',
            width: '9rem',
            show: true,
            orden: 9,
        },
    ],
}
