export const TABLE_COLUMNS = [
    {
        id: 'socio_pedido1.fecha',
        title: 'Fecha',
        prop: 'socio_pedido1.fecha',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        seek: false,
        sort: true,
    },
    {
        id: 'socio_pedido1.codigo',
        title: 'Nro pedido',
        prop: 'socio_pedido1.codigo',
        type: 'text',
        width: '11rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'socio_pedido1.socio1.nombres',
        title: 'Cliente',
        prop: 'socio_pedido1.socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'articulo1.nombre',
        title: 'Artículo',
        type: 'text',
        prop: 'articulo1.nombre',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'pu',
        title: 'Valor unitario',
        type: 'number',
        toRight: true,
        width: '8rem',
        show: true,
        seek: false,
        sort: true,
    },
    {
        id: 'cantidad',
        title: 'Cantidad',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        seek: false,
        sort: true,
    },
    {
        id: 'entregado',
        title: 'Entregado',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        seek: false,
        sort: true,
    },
]
