export default {
    name: 'vCompras',
    title: 'Compras',
    apiPath: 'transacciones',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vCompras:crear',
        },
        {
            text: 'Recuperar',
            action: 'recuperarGuardado',
            permiso: 'vCompras:crear',
            tipo: '2',
            showIfAvance: 'mCompra',
        },
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '8rem',
            show: true,
            orden: 1,
        },
        {
            id: 'guia',
            title: 'Guía',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'factura',
            title: 'Factura',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'socio',
            title: 'Proveedor',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '15rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'pago_condicion',
            title: 'Condición de pago',
            prop: 'pago_condicion1.nombre',
            type: 'select',
            systemKey: 'pago_condiciones',
            width: '12rem',
            show: true,
            orden: 5,
        },
        {
            id: 'moneda',
            title: 'Moneda',
            prop: 'moneda1.nombre',
            type: 'related',
            relatedUrl: 'monedas',
            width: '8rem',
            show: true,
            seek: true,
            orden: 6,
        },
        {
            id: 'monto',
            title: 'Importe',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
            orden: 7,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'transaccion_estados',
            format: 'estado',
            width: '7rem',
            show: true,

            orden: 8,
        },
        {
            id: 'socio_pedido1.codigo',
            title: 'Nro pedido',
            prop: 'socio_pedido1.codigo',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 9,
        },
    ],

    tableRowActions: [
        {
            label: 'Ver',
            icon: 'fa-regular fa-folder-open',
            action: 'ver',
            permiso: 'vCompras:ver',
        },
        {
            label: 'Editar',
            icon: 'fa-solid fa-pen-to-square',
            action: 'editar',
            permiso: 'vCompras:editar',
            ocultar: { estado: 2 },
        },
    ],
}
