export const HEADER_ACTIONS = [
    {
        text: 'Nuevo',
        action: 'nuevo',
        permiso: 'vVentas:crear',
    },
    {
        text: 'Recuperar',
        action: 'recuperarGuardado',
        permiso: 'vVentas:crear',
        tipo: '2',
        showIfAvance: 'mVenta',
    },
]

export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        type: 'date',
        format: 'date',
        width: '10rem',
        show: true,
        sort: true,
    },
    {
        id: 'guia',
        title: 'Guía',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'socio1.nombres',
        title: 'Cliente',
        prop: 'socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'pago_condicion',
        title: 'Condición de pago',
        prop: 'pago_condicion1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        sort: true,
    },
    {
        id: 'moneda1.nombre',
        title: 'Moneda',
        prop: 'moneda1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'monto',
        title: 'Importe',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'estado',
        title: 'Estado',
        type: 'select',
        prop: 'estado1.nombre',
        format: 'estado',
        width: '7rem',
        show: true,
        sort: true,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver',
        icon: 'fa-regular fa-folder-open',
        action: 'ver',
        permiso: 'vVentas:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vVentas:editar',
        ocultar: { estado: 2 },
    },
    {
        label: 'Control de despacho',
        icon: 'fa-solid fa-star',
        action: 'controlDespacho',
        permiso: 'vVentas:controlDespacho',
    },
]
