export const HEADER_ACTIONS = [
    {
        text: 'Nuevo',
        action: 'nuevo',
        permiso: 'vHelpdeskTickets:crear',
    },
]

export const TABLE_COLUMNS = [
    {
        id: 'nombre',
        title: 'Nombre',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 1,
    },
    {
        id: 'descripcion',
        title: 'Descripción',
        type: 'text',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'socio1.nombres',
        title: 'Cliente',
        prop: 'socio1.nombres',
        type: 'text',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'articulo1.nombre',
        title: 'Producto',
        prop: 'articulo1.nombre',
        type: 'text',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'reclamo_fecha',
        title: 'Fecha de reclamo',
        format: 'date',
        type: 'date',
        width: '10rem',
        show: true,
        sort: true,
        orden: 5,
    },
    {
        id: 'reclamo_fuente',
        title: 'Fuente de reclamo',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'createdAt',
        title: 'Creado el',
        format: 'datetime',
        type: 'datetime',
        width: '10rem',
        show: true,
        sort: true,
        orden: 7,
    },
    {
        id: 'createdBy1.nombres',
        title: 'Creado por',
        prop: 'createdBy1.nombres',
        type: 'text',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 8,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vHelpdeskTickets:editar',
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'eliminar',
        permiso: 'vHelpdeskTickets:eliminar',
        ocultar: { estandar: true },
    },
]
