export default {
    name: 'vVentaItems',
    title: 'Artículos vendidos',
    apiPath: 'transaccion_items',

    headerActions: [
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'transaccion1.fecha',
            title: 'Fecha',
            type: 'date',
            prop: 'transaccion1.fecha',
            format: 'date',
            width: '8rem',
            show: true,
            sort: true,
            orden: 1,
        },
        {
            id: 'transaccion1.guia',
            title: 'Guía',
            type: 'text',
            prop: 'transaccion1.guia',
            width: '8rem',
            show: true,
            seek: true,
            sort: true,
            orden: 2,
        },
        {
            id: 'transaccion1.factura',
            title: 'Factura',
            type: 'text',
            prop: 'transaccion1.factura',
            width: '8rem',
            show: true,
            seek: true,
            sort: true,
            orden: 3,
        },
        {
            id: 'transaccion1.socio1.nombres',
            title: 'Cliente',
            prop: 'transaccion1.socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            width: '15rem',
            show: true,
            seek: true,
            sort: true,
            orden: 4,
        },
        {
            id: 'articulo1.nombre',
            title: 'Artículo',
            type: 'text',
            prop: 'articulo1.nombre',
            width: '20rem',
            show: true,
            seek: true,
            sort: true,
            orden: 5,
        },
        {
            id: 'cantidad',
            title: 'Cantidad',
            type: 'number',
            format: 'decimal',
            width: '8rem',
            show: true,
            sort: true,
            orden: 6,
        },
        {
            id: 'pu',
            title: 'Valor unitario',
            type: 'number',
            format: 'decimal',
            width: '8rem',
            show: true,
            sort: true,
            orden: 7,
        },
        {
            id: 'lote',
            title: 'Lote',
            type: 'select',
            width: '8rem',
            show: true,
            sort: true,
            orden: 8,
        },
        {
            id: 'fv',
            title: 'Fecha de vencimiento',
            type: 'date',
            format: 'date',
            width: '8rem',
            show: true,
            sort: true,
            orden: 9,
        },
    ],
}

