export default {
    name: 'vArticulos',
    title: 'Artículos',
    apiPath: 'articulos',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vArticulos:crear',
        },
        {
            icon: 'fa-solid fa-file-excel',
            text: 'Importar',
            action: 'abrirExcel',
            permiso: 'vArticulos:importar',
            tipo: '2',
        },
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'id',
            title: 'id',
            type: 'text',
            width: '5rem',
            show: false,
            orden: 1,
        },
        {
            id: 'nombre',
            title: 'Nombre',
            type: 'text',
            width: '25rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'unidad',
            title: 'Unidad',
            type: 'select',
            systemKey: 'unidades',
            editable: true,
            width: '5rem',
            show: true,
            orden: 3,
        },
        {
            id: 'stock',
            title: 'Stock',
            filtrable: false,
            format: 'decimal',
            toRight: true,
            width: '7rem',
            show: true,
            orden: 4,
        },
        {
            id: 'activo',
            title: 'Activo?',
            prop: 'activo1.nombre',
            type: 'select',
            systemKey: 'estados',
            editable: true,
            format: 'yesno',
            width: '8rem',
            show: true,
            orden: 5,
        },
        {
            id: 'codigo_barra',
            title: 'EAN',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            orden: 6,
        },
        {
            id: 'linea',
            title: 'Línea',
            prop: 'linea1.nombre',
            type: 'related',
            relatedUrl: 'articulo_lineas',
            editable: true,
            width: '10rem',
            show: true,
            seek: true,
            orden: 7,
        },
        {
            id: 'categoria',
            title: 'Categoría',
            prop: 'categoria1.nombre',
            type: 'related',
            relatedUrl: 'articulo_categorias',
            editable: true,
            width: '10rem',
            show: true,
            seek: true,
            orden: 8,
        },
        {
            id: 'filtrantes',
            title: 'Sobres en caja',
            type: 'number',
            width: '5rem',
            show: true,
            orden: 9,
        },
        {
            id: 'contenido_neto',
            title: 'Contenido neto (g)',
            type: 'number',
            width: '5rem',
            show: true,
            orden: 10,
        },
        {
            id: 'has_fv',
            title: 'Tiene fecha de vencimiento?',
            prop: 'has_fv1.nombre',
            type: 'select',
            systemKey: 'estados',
            editable: true,
            format: 'yesno',
            width: '8rem',
            show: true,
            orden: 11,
        },
        {
            id: 'igv_afectacion',
            title: 'Tributo',
            prop: 'igv_afectacion1.nombre',
            type: 'select',
            systemKey: 'igv_afectaciones',
            editable: true,
            width: '10rem',
            show: true,
            orden: 12,
        },
        {
            id: 'is_ecommerce',
            title: 'Ecommerce?',
            prop: 'is_ecommerce1.nombre',
            type: 'select',
            format: 'yesno',
            editable: true,
            width: '10rem',
            show: false,
            orden: 13,
        },
        {
            id: 'precio',
            title: 'Precio',
            type: 'number',
            editable: true,
            width: '10rem',
            show: false,
            orden: 14,
        },
        {
            id: 'purchase_ok',
            title: 'Se compra',
            prop: 'purchase_ok1.nombre',
            type: 'select',
            format: 'yesno',
            editable: true,
            width: '8rem',
            show: false,
            orden: 15,
        },
        {
            id: 'sale_ok',
            title: 'Se vende',
            prop: 'sale_ok1.nombre',
            type: 'select',
            format: 'yesno',
            editable: true,
            width: '8rem',
            show: false,
            orden: 16,
        },
        {
            id: 'produce_ok',
            title: 'Se produce',
            prop: 'produce_ok1.nombre',
            type: 'select',
            format: 'yesno',
            editable: true,
            width: '8rem',
            show: false,
            orden: 17,
        },
    ],

    tableBulkActions: [
        {
            icon: 'fa-solid fa-pen-to-square',
            text: 'Editar',
            action: 'vista.editarBulk',
            permiso: 'vArticulos:editarBulk',
        },
        {
            icon: 'fa-solid fa-trash-can',
            text: 'Eliminar',
            action: 'vista.eliminarBulk',
            permiso: 'vArticulos:eliminarBulk',
        },
    ],

    tableRowActions: [
        {
            label: 'Editar',
            icon: 'fa-solid fa-pen-to-square',
            action: 'editar',
            permiso: 'vArticulos:editar',
        },
        {
            label: 'Actualizar fotos',
            icon: 'fa-solid fa-image',
            action: 'openUploadFiles',
            permiso: 'vArticulos:actualizarFotos',
        },
        {
            label: 'Eliminar',
            icon: 'fa-solid fa-trash-can',
            action: 'vista.eliminar',
            permiso: 'vArticulos:eliminar',
        },
        {
            label: 'Clonar',
            icon: 'fa-solid fa-copy',
            action: 'clonar',
            permiso: 'vArticulos:clonar',
        },
        {
            label: 'Ver kardex',
            icon: 'fa-solid fa-table-list',
            action: 'verKardex',
            permiso: 'vArticulos:kardex',
        },
        {
            label: 'Ver lotes',
            icon: 'fa-solid fa-table-list',
            action: 'verLotes',
            permiso: 'vArticulos:lotes',
        },
        {
            label: 'Ajuste stock',
            icon: 'fa-solid fa-wrench',
            action: 'ajusteStock',
            permiso: 'vArticulos:ajusteStock',
        },
    ],
}
