export const HEADER_ACTIONS = [
    {
        text: 'Ver cuarentena',
        action: 'verCuarentena',
        permiso: 'vPtsIngresos:verCuarentena',
        tipo: '2',
    },
]

export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
        orden: 1,
    },
    {
        id: 'produccion_orden1.linea1.nombre',
        title: 'Tipo',
        prop: 'produccion_orden1.linea1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'maquina1.nombre',
        title: 'Máquina',
        prop: 'maquina1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'articulo1.nombre',
        title: 'Producto',
        prop: 'articulo1.nombre',
        type: 'text',
        width: '25rem',
        show: true,
        seek: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'lote',
        title: 'Lote',
        type: 'text',
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
        orden: 5,
    },
    {
        id: 'fv',
        title: 'F. vencimiento',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'cantidad',
        title: 'Cantidad',
        type: 'number',
        format: 'number',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
        orden: 7,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver trazabilidad',
        icon: 'fa-solid fa-diagram-project',
        action: 'verTrazabilidad',
        permiso: 'vPtsIngresos:trazabilidad',
    },
]
