export const COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'produccion_orden1.linea1.nombre',
        title: 'Tipo',
        prop: 'produccion_orden1.linea1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        sort: true,
    },
    {
        id: 'maquina1.nombre',
        title: 'Máquina',
        prop: 'maquina1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'articulo1.nombre',
        title: 'Producto',
        prop: 'articulo1.nombre',
        type: 'text',
        width: '25rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'lote',
        title: 'Lote',
        type: 'text',
        width: '7rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'fv',
        title: 'F. vencimiento',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
    },
    {
        id: 'cantidad',
        title: 'Cantidad',
        type: 'number',
        format: 'number',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
    },
]

export const TABLE_ROW_OPTIONS = [
    {
        label: 'Ver trazabilidad',
        icon: 'fa-solid fa-diagram-project',
        action: 'verTrazabilidad',
        permiso: 'vPtsIngresos:trazabilidad',
    },
]
