export const HEADER_ACTIONS = [
    {
        text: 'Nuevo',
        action: 'nuevo',
        permiso: 'vProduccionHistorial:crear',
    },
    {
        text: 'Salida de insumos',
        action: 'salidaInsumosCompartidos',
        permiso: 'vProduccionHistorial:salidaInsumos',
        tipo: '2',
    },
]

export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        type: 'date',
        format: 'date',
        width: '10rem',
        show: true,
        sort: true,
        orden: 1,
    },
    {
        id: 'articulo1.nombre',
        title: 'Producto',
        prop: 'articulo1.nombre',
        type: 'text',
        width: '25rem',
        show: true,
        seek: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'cantidad',
        title: 'Cantidad planificada',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'estado',
        title: 'Estado',
        prop: 'estado1.nombre',
        type: 'select',
        format: 'estado',
        width: '8rem',
        show: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'productos_terminados',
        title: 'Productos terminados',
        type: 'number',
        format: 'decimal',
        filtrable: false,
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
        orden: 5,
    },
    {
        id: 'linea1.nombre',
        title: 'Tipo de producción',
        prop: 'linea1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'maquina1.nombre',
        title: 'Máquina',
        prop: 'maquina1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 7,
    },
    {
        id: 'responsable1.nombres',
        title: 'Responsable',
        prop: 'responsable1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 8,
    },
    {
        id: 'inicio',
        title: 'Hora inicio',
        format: 'datetime',
        width: '11rem',
        show: true,
        filtrable: false,
        orden: 9,
    },
    {
        id: 'fin',
        title: 'Hora fin',
        format: 'datetime',
        width: '11rem',
        show: true,
        filtrable: false,
        orden: 10,
    },
    {
        id: 'estado_calidad_revisado',
        title: 'Control de pesos',
        prop: 'estado_calidad_revisado1.nombre',
        format: 'estado',
        filtrable: false,
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 11,
    },
    {
        id: 'estado_cf_ppc',
        title: 'Control del PPC',
        prop: 'estado_cf_ppc1.nombre',
        format: 'estado',
        filtrable: false,
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 12,
    },
    {
        id: 'createdBy1.nombres',
        title: 'Creado por',
        prop: 'createdBy1.nombres',
        filtrable: false,
        width: '10rem',
        show: true,
        orden: 13,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver',
        icon: 'fa-solid fa-folder-open',
        action: 'ver',
        permiso: 'vProduccionHistorial:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vProduccionHistorial:editar',
        ocultar: { estado: 2 },
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'eliminar',
        permiso: 'vProduccionHistorial:eliminar',
        ocultar: { estado: 2 },
    },
    {
        label: 'Terminar',
        icon: 'fa-solid fa-check-double',
        action: 'terminar',
        permiso: 'vProduccionHistorial:terminar',
        ocultar: { estado: 2 },
    },
    {
        label: 'Abrir',
        icon: 'fa-solid fa-check-double',
        action: 'abrir',
        permiso: 'vProduccionHistorial:terminar',
        ocultar: { estado: 1 },
    },
    {
        label: 'Salida de insumos',
        icon: 'fa-regular fa-circle-down',
        action: 'salidaInsumos',
        permiso: 'vProduccionHistorial:salidaInsumos',
    },
    {
        label: 'Productos terminados',
        icon: 'fa-solid fa-boxes-stacked',
        action: 'productosTerminados',
        permiso: 'vProduccionHistorial:productosTerminados',
    },
    {
        label: 'Ver trazabilidad',
        icon: 'fa-solid fa-diagram-project',
        action: 'verTrazabilidad',
        permiso: 'vProduccionHistorial:trazabilidad',
    },
    {
        label: 'Control de pesos',
        icon: 'fa-solid fa-star',
        action: 'controlPesos',
        permiso: 'vProduccionHistorial:controlPesos',
    },
    {
        label: 'Control del PPC',
        icon: 'fa-solid fa-star',
        action: 'controlPpc',
        permiso: 'vProduccionHistorial:controlPpc',
    },
]
