export default {
    name: 'vKardex',
    title: 'Kardex',
    apiPath: 'kardex',
    headerActions: [],
    tableColumns: [
        { id: 'fecha', title: 'Fecha', prop: 'fecha1', width: '8rem', show: true, sort: true },
        {
            id: 'tipo',
            title: 'Operación',
            prop: 'tipo1.nombre',
            width: '15rem',
            show: true,
        },
        { id: 'lote', title: 'Lote', width: '8rem', show: true, sort: true },
        {
            id: 'fv',
            title: 'Fecha vencimiento',
            prop: 'fv1',
            width: '8rem',
            show: true,
        },
        { id: 'vu_real', title: 'Valor unitario', toRight: true, width: '8rem', show: true },
        { id: 'pu', title: 'Precio unitario', toRight: true, width: '8rem', show: true },
        {
            id: 'cantidad',
            title: 'Cantidad',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
        },
        { id: 'maquina', title: 'Máquina', prop: 'maquina1.nombre', width: '8rem', show: true },
        {
            id: 'transaccion1.socio',
            title: 'Socio comercial',
            prop: 'transaccion1.socio1.nombres',
            width: '8rem',
            show: true,
        },
        {
            id: 'transaccion1.guia',
            title: 'Guía',
            prop: 'transaccion1.guia',
            width: '8rem',
            show: true,
        },
        { id: 'observacion', title: 'Observación', width: '8rem', show: true },
    ],
    tableRowActions: [
        {
            label: 'Ver compra',
            icon: 'fa-regular fa-folder-open',
            action: 'verCompra',
            ocultar: { tipo: { op: '!=', val: 1 } },
        },
        {
            label: 'Ver venta',
            icon: 'fa-regular fa-folder-open',
            action: 'verCompra',
            ocultar: { tipo: { op: '!=', val: 5 } },
        },
    ],
}
