export const HEADER_ACTIONS = [
    {
        text: 'Nuevo',
        action: 'nuevo',
        permiso: 'vVentaPedidos:crear',
    },
    {
        text: 'Recuperar',
        action: 'recuperarGuardado',
        permiso: 'vVentaPedidos:crear',
        tipo: '2',
        showIfAvance: 'mVentaPedido',
    },
    {
        text: 'Descargar plantilla',
        action: 'descargarPlantilla',
        tipo: '2',
    },
    {
        text: 'Ver productos pedidos',
        action: 'verPedidos',
        permiso: 'vVentaPedidos:verProductosPedidos',
        tipo: '2',
    },
    {
        icon: 'fa-solid fa-download',
        text: 'Exportar página actual',
        action: 'vista.downloadActualTablePage',
        tipo: '2',
    }
]

export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        format: 'date',
        type: 'date',
        width: '10rem',
        show: true,
        sort: true,
        orden: 1,
    },
    {
        id: 'codigo',
        title: 'Nro pedido',
        type: 'text',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'socio1.nombres',
        title: 'Cliente',
        prop: 'socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'pago_condicion',
        title: 'Condición de pago',
        prop: 'pago_condicion1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'moneda1.nombre',
        title: 'Moneda',
        prop: 'moneda1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        seek: false,
        sort: true,
        orden: 5,
    },
    {
        id: 'monto',
        title: 'Importe',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'estado',
        title: 'Estado',
        prop: 'estado1.nombre',
        type: 'select',
        format: 'estado',
        width: '8rem',
        show: true,
        sort: true,
        orden: 7,
    },
    {
        id: 'pagado',
        title: 'Pagado?',
        prop: 'pagado1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: true,
        orden: 8,
    },
    {
        id: 'listo',
        title: 'Listo para entrega?',
        prop: 'listo1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: true,
        orden: 9,
    },
    {
        id: 'entregado',
        title: 'Entregado?',
        prop: 'entregado1.nombre',
        type: 'select',
        format: 'yesno',
        width: '8rem',
        show: true,
        orden: 10,
    },
    {
        id: 'origin',
        title: 'Origen',
        width: '10rem',
        type: 'text',
        show: true,
        orden: 11,
    },
    {
        id: 'createdBy1.nombres',
        title: 'Creado por',
        prop: 'createdBy1.nombres',
        filtrable: false,
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 12,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver',
        icon: 'fa-regular fa-folder-open',
        action: 'ver',
        permiso: 'vVentaPedidos:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vVentaPedidos:editar',
        ocultar: { estado: ['0', '2'], origin: 'ecommerce' },
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'vista.eliminar',
        permiso: 'vVentaPedidos:eliminar',
        ocultar: { pagado: true, origin: 'ecommerce' },
    },
    {
        label: 'Exportar en PDF',
        icon: 'fa-regular fa-file-pdf',
        action: 'generarPdf',
        permiso: 'vVentaPedidos:generarPdf',
    },
    {
        label: 'Confirmar pago',
        icon: 'fa-solid fa-hand-holding-dollar',
        action: 'confirmarPago',
        permiso: 'vVentaPedidos:confirmarPago',
        ocultar: { pagado: true, pago_condicion: ['2', '3'] },
    },
    {
        label: 'Marcar como listo',
        icon: 'fa-solid fa-check-double',
        action: 'confirmarListo',
        permiso: 'vVentaPedidos:confirmarListo',
        ocultar: { listo: true, pagado: false, pago_condicion: ['2', '3'] },
    },
    {
        label: 'Marcar como listo',
        icon: 'fa-solid fa-check-double',
        action: 'confirmarListo',
        permiso: 'vVentaPedidos:confirmarListo',
        ocultar: { listo: true, pago_condicion: 1 },
    },
    {
        label: 'Confirmar entrega',
        icon: 'fa-regular fa-truck',
        action: 'confirmarEntrega',
        permiso: 'vVentaPedidos:confirmarEntrega',
        ocultar: { entregado: true, listo: false },
    },
    {
        label: 'Entregar mercadería',
        icon: 'fa-regular fa-circle-down',
        action: 'entregarMercaderia',
        permiso: 'vVentaPedidos:entregarMercaderia',
        ocultar: { estado: ['0', '2'] },
    },
]
