export default {
    apiPath: 'comprobantes',
    detailPath: 'comprobante_id',
    detailViewName: 'vComprobante',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: ['vComprobantes:crear'],
        },
    ],

    tableColumns: [
        {
            id: 'fecha_emision',
            title: 'Fecha Emisión',
            prop: 'fecha_emision',
            type: 'date',
            width: '10rem',
            show: true,
            orden: 1,
        },
        {
            id: 'serie_correlativo',
            title: 'Número',
            prop: 'serie_correlativo',
            type: 'text',
            width: '12rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'socio',
            title: 'Proveedor',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '20rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'monto',
            title: 'Monto',
            prop: 'monto',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '10rem',
            show: true,
            orden: 4,
        },
        // {
        //     id: 'estado',
        //     title: 'Estado',
        //     prop: 'estado',
        //     type: 'text',
        //     width: '10rem',
        //     show: true,
        //     orden: 5,
        // },
    ],
}
