export default {
    id: 'produccion',
    label: 'Producción',
    icon: 'fa-solid fa-oil-well',
    path: 'produccion',
    children: [
        {
            label: 'Lista de materiales',
            goto: 'vMrpBom',
            path: 'mrp-bom',
            view: 'produccion/mrp_bom/vMrpBom.vue',
            permisos: [
                { id: 'vMrpBom:listar', label: 'Listar' },
                { id: 'vMrpBom:crear', label: 'Crear' },
                { id: 'vMrpBom:ver', label: 'Ver' },
                { id: 'vMrpBom:editar', label: 'Editar' },
                { id: 'vMrpBom:eliminar', label: 'Eliminar' },
            ],
        },
        {
            label: 'Programa',
            goto: 'vPrograma',
            path: 'programa',
            view: 'produccion/vPrograma.vue',
            permisos: [
                { id: 'vPrograma:listar', label: 'Listar' },
                { id: 'vPrograma:crear', label: 'Crear' },
                { id: 'vPrograma:ver', label: 'Ver' },
                { id: 'vPrograma:editar', label: 'Editar' },
                { id: 'vPrograma:eliminar', label: 'Eliminar' },
                { id: 'vPrograma:abrirCerrar', label: 'Abrir y cerrar' },
                { id: 'vPrograma:salidaInsumos', label: 'Salida insumos' },
                { id: 'vPrograma:productosTerminados', label: 'Productos terminados' },
                { id: 'vPrograma:verProductosPedidos', label: 'Ver productos pedidos' },
                {
                    id: 'vPrograma:salidaInsumosCompartidos',
                    label: 'Salida de insumos compartidos',
                },
            ],
        },
        {
            label: 'Órdenes de producción',
            goto: 'vProduccionHistorial',
            path: 'ordenes',
            view: 'produccion/historial/vProduccionHistorial.vue',
            permisos: [
                { id: 'vProduccionHistorial:listar', label: 'Listar' },
                { id: 'vProduccionHistorial:crear', label: 'Crear' },
                { id: 'vProduccionHistorial:ver', label: 'Ver' },
                { id: 'vProduccionHistorial:editar', label: 'Editar' },
                { id: 'vProduccionHistorial:eliminar', label: 'Eliminar' },
                { id: 'vProduccionHistorial:abrirCerrar', label: 'Abir y cerrar' },
                { id: 'vProduccionHistorial:salidaInsumos', label: 'Salida insumos' },
                {
                    id: 'vProduccionHistorial:productosTerminados',
                    label: 'Productos terminados',
                },
                { id: 'vProduccionHistorial:trazabilidad', label: 'Ver trazabilidad' },
                { id: 'vProduccionHistorial:controlPesos', label: 'Control de pesos' },
                { id: 'vProduccionHistorial:controlPpc', label: 'Control del PPC' },
                {
                    id: 'vProduccionHistorial:verProductosPedidos',
                    label: 'Ver productos pedidos',
                },
                {
                    id: 'vProduccionHistorial:salidaInsumosCompartidos',
                    label: 'Salida de insumos compartidos',
                },
            ],
        },
        {
            label: 'Ingreso de productos',
            goto: 'vPtsIngresos',
            path: 'ingresos',
            view: 'produccion/ingreso_pt/vPtsIngresos.vue',
            permisos: [
                { id: 'vPtsIngresos:listar', label: 'Listar' },
                { id: 'vPtsIngresos:verCuarentena', label: 'Ver cuarentena' },
                { id: 'vPtsIngresos:ingresarPts', label: 'Ingresar productos terminados' },
                { id: 'vPtsIngresos:liberar_lote', label: 'Liberar lote' },
                { id: 'vPtsIngresos:trazabilidad', label: 'Ver trazabilidad' },
            ],
        },
        {
            label: 'Reporte',
            goto: 'vReporteProduccion',
            path: 'reporte',
            view: 'produccion/vReporteProduccion.vue',
            permisos: [{ id: 'vReporteProduccion:listar', label: 'Listar' }],
        },
    ],
}
