export default {
    id: 'produccion',
    label: 'Producción',
    icon: 'fa-solid fa-oil-well',
    path: 'produccion',
    children: [
        {
            label: 'Lista de materiales',
            goto: 'vMrpBom',
            path: 'mrp-bom',
            view: 'produccion/mrp_bom/vMrpBom.vue',
            permisos: [
                { id: 'vMrpBom:listar', label: 'Listar' },
                { id: 'vMrpBom:crear', label: 'Crear' },
                { id: 'vMrpBom:ver', label: 'Ver' },
                { id: 'vMrpBom:editar', label: 'Editar' },
                { id: 'vMrpBom:eliminar', label: 'Eliminar' },
            ],
        },
        {
            label: 'Programa',
            goto: 'vPrograma',
            path: 'programa',
            view: 'produccion/vPrograma.vue',
            permisos: [
                { id: 'vPrograma:listar', label: 'Listar' },
                { id: 'vPrograma:crear', label: 'Crear' },
                { id: 'vPrograma:ver', label: 'Ver' },
                { id: 'vPrograma:editar', label: 'Editar' },
                { id: 'vPrograma:eliminar', label: 'Eliminar' },
                { id: 'vPrograma:abrirCerrar', label: 'Abrir y cerrar' },
                { id: 'vPrograma:salidaInsumos', label: 'Salida insumos' },
                { id: 'vPrograma:productosTerminados', label: 'Productos terminados' },
                { id: 'vPrograma:verProductosPedidos', label: 'Ver productos pedidos' },
                {
                    id: 'vPrograma:salidaInsumosCompartidos',
                    label: 'Salida de insumos compartidos',
                },
            ],
        },
        {
            label: 'Órdenes de producción',
            goto: 'vProduccionOrdenes',
            path: 'ordenes',
            view: '_user/produccion_ordenes/vProduccionOrdenes.vue',
            permisos: [
                { id: 'vProduccionOrdenes:listar', label: 'Listar' },
                { id: 'vProduccionOrdenes:listar:responsable', label: 'Listar asignados' },
                { id: 'vProduccionOrdenes:crear', label: 'Crear' },
                { id: 'vProduccionOrdenes:ver', label: 'Ver' },
                { id: 'vProduccionOrdenes:editar', label: 'Editar' },
                { id: 'vProduccionOrdenes:eliminar', label: 'Eliminar' },
                { id: 'vProduccionOrdenes:abrirCerrar', label: 'Abir y cerrar' },
                { id: 'vProduccionOrdenes:salidaInsumos', label: 'Salida insumos' },
                {
                    id: 'vProduccionOrdenes:productosTerminados',
                    label: 'Productos terminados',
                },
                { id: 'vProduccionOrdenes:trazabilidad', label: 'Ver trazabilidad' },
                { id: 'vProduccionOrdenes:controlPesos', label: 'Control de pesos' },
                { id: 'vProduccionOrdenes:controlPpc', label: 'Control del PPC' },
                {
                    id: 'vProduccionOrdenes:verProductosPedidos',
                    label: 'Ver productos pedidos',
                },
                {
                    id: 'vProduccionOrdenes:salidaInsumosCompartidos',
                    label: 'Salida de insumos compartidos',
                },
            ],
            children: [
                {
                    label: 'Detalle OT',
                    goto: 'vProduccionOrden',
                    path: ':produccion_orden_id',
                    view: '_user/produccion_orden/vProduccionOrden.vue',
                    permission: 'vProduccionOrdenes:ver',
                    viewType: 'detail',
                },
            ],
        },
        {
            label: 'Ingreso de productos',
            goto: 'vPtsIngresos',
            path: 'ingresos',
            view: 'produccion/ingreso_pt/vPtsIngresos.vue',
            permisos: [
                { id: 'vPtsIngresos:listar', label: 'Listar' },
                { id: 'vPtsIngresos:verCuarentena', label: 'Ver cuarentena' },
                { id: 'vPtsIngresos:ingresarPts', label: 'Ingresar productos terminados' },
                { id: 'vPtsIngresos:liberar_lote', label: 'Liberar lote' },
                { id: 'vPtsIngresos:trazabilidad', label: 'Ver trazabilidad' },
            ],
        },
        {
            label: 'Reporte',
            goto: 'vReporteProduccion',
            path: 'reporte',
            view: 'produccion/vReporteProduccion.vue',
            permisos: [{ id: 'vReporteProduccion:listar', label: 'Listar' }],
        },
    ],
}
