export default {
    id: 'inventario',
    label: 'Inventario',
    icon: 'fa-solid fa-boxes-stacked',
    path: 'inventario',
    children: [
        {
            label: 'Líneas de productos',
            goto: 'vProductoLineas',
            path: 'lineas',
            view: 'inventario/lineas/vProductoLineas.vue',
            permisos: [
                { id: 'vProductoLineas:listar', label: 'Listar' },
                { id: 'vProductoLineas:crear', label: 'Crear' },
                { id: 'vProductoLineas:editar', label: 'Editar' },
                { id: 'vProductoLineas:eliminar', label: 'Eliminar' },
                { id: 'vProductoLineas:actualizarFotos', label: 'Actualizar fotos' },
            ],
        },
        {
            label: 'Categorías',
            goto: 'vArticuloCategorias',
            path: 'categorias',
            view: 'inventario/categorias/vArticuloCategorias.vue',
            permisos: [
                { id: 'vArticuloCategorias:listar', label: 'Listar' },
                { id: 'vArticuloCategorias:crear', label: 'Crear' },
                { id: 'vArticuloCategorias:editar', label: 'Editar' },
                { id: 'vArticuloCategorias:eliminar', label: 'Eliminar' },
                { id: 'vArticuloCategorias:actualizarFotos', label: 'Actualizar fotos' },
            ],
        },
        {
            label: 'Artículos',
            goto: 'vArticulos',
            path: 'articulos',
            view: '_user/articulos/vArticulos.vue',
            permisos: [
                { id: 'vArticulos:listar', label: 'Listar' },
                { id: 'vArticulos:ver', label: 'Ver' },
                { id: 'vArticulos:crear', label: 'Crear' },
                { id: 'vArticulos:editar', label: 'Editar' },
                { id: 'vArticulos:eliminar', label: 'Eliminar' },
                { id: 'vArticulos:actualizarFotos', label: 'Actualizar fotos' },
                { id: 'vArticulos:clonar', label: 'Clonar' },
                { id: 'vArticulos:listaMateriales', label: 'Lista de materiales' },
                { id: 'vArticulos:kardex', label: 'Ver kardex' },
                { id: 'vArticulos:lotes', label: 'Ver Lotes' },
                { id: 'vArticulos:kardexDelete', label: 'Eliminar movimiento kardex' },
                { id: 'vArticulos:ajusteStock', label: 'Ajuste stock' },
                { id: 'vArticulos:importar', label: 'Importar' },
                { id: 'vArticulos:editarBulk', label: 'Editar masivo' },
                { id: 'vArticulos:eliminarBulk', label: 'Eliminar masivo' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vArticulo',
                    path: ':articulo_id',
                    view: '_user/articulo/vArticulo.vue',
                    permission: 'vArticulos:ver',
                    viewType: 'detail',
                    children: [
                        {
                            label: 'Historial de movimientos',
                            goto: 'vArticuloKardex',
                            path: 'kardex',
                            view: '_user/kardex/vKardex.vue',
                            permission: 'vArticulos:kardex',
                        },
                    ],
                },
            ],
        },
        {
            label: 'Existencias',
            goto: 'vStock',
            path: 'stock',
            view: '_user/stock/vStock.vue',
            permisos: [{ id: 'vStock:listar', label: 'Listar' }],
        },
        {
            label: 'Historial de movimientos',
            goto: 'vKardex',
            path: 'kardex',
            view: '_user/kardex/vKardex.vue',
            permisos: [
                { id: 'vKardex:listar', label: 'Listar' },
                { id: 'vKardex:eliminar', label: 'Eliminar' },
            ],
        },
        {
            label: 'Historial de consumos',
            goto: 'vConsumo',
            path: 'consumo',
            view: '_user/consumo/vConsumo.vue',
            permisos: [{ id: 'vConsumo:listar', label: 'Listar' }],
        },
    ],
}
