export default {
    id: 'compras',
    label: 'Compras',
    icon: 'fa-solid fa-cart-shopping',
    path: 'compras',
    children: [
        {
            label: 'Proveedores',
            goto: 'vProveedores',
            path: 'proveedores',
            view: '_user/socios/vSocios.vue',
            permisos: [
                { id: 'vProveedores:listar', label: 'Listar' },
                { id: 'vProveedores:crear', label: 'Crear' },
                { id: 'vProveedores:ver', label: 'Ver' },
                { id: 'vProveedores:editar', label: 'Editar' },
                { id: 'vProveedores:eliminar', label: 'Eliminar' },
                { id: 'vProveedores:editarBulk', label: 'Editar masivo' },
                { id: 'vProveedores:eliminarBulk', label: 'Eliminar masivo' },
            ],
        },
        {
            label: 'Precios',
            goto: 'vCompraPrecios',
            path: 'precios-compra',
            view: '_user/compra_precios/vCompraPrecios.vue',
            permisos: [
                { id: 'vCompraPrecios:listar', label: 'Listar' },
                { id: 'vCompraPrecios:crear', label: 'Crear' },
                { id: 'vCompraPrecios:editar', label: 'Editar' },
                { id: 'vCompraPrecios:eliminar', label: 'Eliminar' },
            ],
        },
        {
            label: 'Pedidos',
            goto: 'vCompraPedidos',
            path: 'pedidos',
            view: '_user/socio_pedidos/vSocioPedidos.vue',
            permisos: [
                { id: 'vCompraPedidos:listar', label: 'Listar' },
                { id: 'vCompraPedidos:crear', label: 'Crear' },
                { id: 'vCompraPedidos:ver', label: 'Ver' },
                { id: 'vCompraPedidos:editar', label: 'Editar' },
                { id: 'vCompraPedidos:eliminar', label: 'Eliminar' },
                { id: 'vCompraPedidos:abrirCerrar', label: 'Abrir y cerrar' },
                { id: 'vCompraPedidos:generarPdf', label: 'Generar PDF' },
                { id: 'vCompraPedidos:recalcularEntregados', label: 'Recalcular entregados' },
                { id: 'vCompraPedidos:ingresarMercaderia', label: 'Ingresar mercadería' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vCompraPedido',
                    path: ':pedido_id',
                    view: '_user/socio_pedido/vSocioPedido.vue',
                    permission: 'vCompraPedidos:ver',
                    viewType: 'detail',
                    children: [
                        {
                            label: 'Recepciones',
                            goto: 'vCompraPedidoTraslados',
                            path: 'recepciones',
                            view: '_user/traslados/vTraslados.vue',
                            permission: 'vCompraPedidos:ingresarMercaderia',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vCompraPedidoTraslado',
                                    path: ':traslado_id',
                                    view: '_user/traslado/vTraslado.vue',
                                    permission: 'vCompraPedidos:ingresarMercaderia',
                                    viewType: 'detail',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            label: 'Pedidos detalle',
            goto: 'vCompraPedidoItems',
            path: 'pedido-items',
            view: '_user/socio_pedido_items/vSocioPedidoItems.vue',
            permisos: [{ id: 'vCompraPedidoItems:listar', label: 'Listar' }],
        },
        {
            label: 'Recepciones',
            goto: 'vCompras',
            path: 'recepciones',
            view: '_user/traslados/vTraslados.vue',
            permisos: [
                { id: 'vCompras:listar', label: 'Listar' },
                { id: 'vCompras:crear', label: 'Crear' },
                { id: 'vCompras:ver', label: 'Ver' },
                { id: 'vCompras:editar', label: 'Editar' },
                { id: 'vCompras:eliminar', label: 'Eliminar' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vCompraTraslado',
                    path: ':traslado_id',
                    view: '_user/traslado/vTraslado.vue',
                    permission: ['vCompras:ver'],
                    viewType: 'detail',
                },
            ],
        },
        {
            label: 'Recepciones detalle',
            goto: 'vCompraItems',
            path: 'recepciones-items',
            view: '_user/traslado_items/vTrasladoItems.vue',
            permisos: [
                { id: 'vCompraItems:listar', label: 'Listar' },
                { id: 'vCompraItems:inspeccion', label: 'Inspeccionar' },
            ],
        },
    ],
}
