export default {
    id: 'compras',
    label: 'Compras',
    icon: 'fa-solid fa-cart-shopping',
    path: 'compras',
    children: [
        {
            label: 'Proveedores',
            goto: 'vProveedores',
            path: 'proveedores',
            view: 'socios/vSocios.vue',
            permisos: [
                { id: 'vProveedores:listar', label: 'Listar' },
                { id: 'vProveedores:crear', label: 'Crear' },
                { id: 'vProveedores:ver', label: 'Ver' },
                { id: 'vProveedores:editar', label: 'Editar' },
                { id: 'vProveedores:eliminar', label: 'Eliminar' },
                { id: 'vProveedores:editarBulk', label: 'Editar masivo' },
                { id: 'vProveedores:eliminarBulk', label: 'Eliminar masivo' },
            ],
        },
        {
            label: 'Precios',
            goto: 'vCompraPrecios',
            path: 'precios-compra',
            view: '_user/compra_precios/vCompraPrecios.vue',
            permisos: [
                { id: 'vCompraPrecios:listar', label: 'Listar' },
                { id: 'vCompraPrecios:crear', label: 'Crear' },
                { id: 'vCompraPrecios:editar', label: 'Editar' },
                { id: 'vCompraPrecios:eliminar', label: 'Eliminar' },
            ],
        },
        {
            label: 'Pedidos',
            goto: 'vCompraPedidos',
            path: 'pedidos',
            view: '_user/socio_pedidos/vSocioPedidos.vue',
            permisos: [
                { id: 'vCompraPedidos:listar', label: 'Listar' },
                { id: 'vCompraPedidos:crear', label: 'Crear' },
                { id: 'vCompraPedidos:ver', label: 'Ver' },
                { id: 'vCompraPedidos:editar', label: 'Editar' },
                { id: 'vCompraPedidos:eliminar', label: 'Eliminar' },
                { id: 'vCompraPedidos:generarPdf', label: 'Generar PDF' },
                { id: 'vCompraPedidos:ingresarMercaderia', label: 'Ingresar mercadería' },
                { id: 'vCompraPedidos:abrir', label: 'Abrir' },
                { id: 'vCompraPedidos:cerrar', label: 'Cerrar' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vCompraPedido',
                    path: ':pedido_id',
                    view: '_user/socio_pedido/vSocioPedido.vue',
                    permission: 'vCompraPedidos:ver',
                    viewType: 'detail',
                    children: [
                        {
                            label: 'Recepciones',
                            goto: 'vCompraPedidoRecepciones',
                            path: 'recepciones',
                            view: '_user/traslados/vTraslados.vue',
                            permission: 'vCompraPedidos:ingresarMercaderia',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vCompraPedidoRecepcion',
                                    path: ':traslado_id',
                                    view: '_user/traslado/vTraslado.vue',
                                    permission: 'vCompraPedidos:ingresarMercaderia',
                                    viewType: 'detail',
                                },
                            ],
                        },
                        {
                            label: 'Entregas',
                            goto: 'vCompraPedidoEntregas',
                            path: 'entregas',
                            view: '_user/traslados/vTraslados.vue',
                            permission: 'vCompraPedidos:ingresarMercaderia',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vCompraPedidoEntrega',
                                    path: ':traslado_id',
                                    view: '_user/traslado/vTraslado.vue',
                                    permission: 'vCompraPedidos:ingresarMercaderia',
                                    viewType: 'detail',
                                },
                            ],
                        },
                        {
                            label: 'Facturas proveedor',
                            goto: 'vCompraPedidoComprobantes',
                            path: 'comprobantes',
                            view: '_user/comprobantes/vComprobantes.vue',
                            permission: 'vCompraComprobantes:ver',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vCompraPedidoComprobante',
                                    path: ':comprobante_id',
                                    view: '_user/comprobante/vComprobante.vue',
                                    permission: 'vCompraComprobantes:ver',
                                    viewType: 'detail',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            label: 'Pedidos detalle',
            goto: 'vCompraPedidoItems',
            path: 'pedido-items',
            view: '_user/socio_pedido_items/vSocioPedidoItems.vue',
            permisos: [{ id: 'vCompraPedidoItems:listar', label: 'Listar' }],
        },
        {
            label: 'Recepciones',
            goto: 'vCompras',
            path: 'recepciones',
            view: '_user/traslados/vTraslados.vue',
            permisos: [
                { id: 'vCompras:listar', label: 'Listar' },
                { id: 'vCompras:crear', label: 'Crear' },
                { id: 'vCompras:ver', label: 'Ver' },
                { id: 'vCompras:editar', label: 'Editar' },
                { id: 'vCompras:eliminar', label: 'Eliminar' },
                { id: 'vCompras:abrir', label: 'Abrir' },
                { id: 'vCompras:cerrar', label: 'Cerrar' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vCompraTraslado',
                    path: ':traslado_id',
                    view: '_user/traslado/vTraslado.vue',
                    permission: ['vCompras:ver'],
                    viewType: 'detail',
                    children: [
                        {
                            label: 'Facturas de proveedor',
                            goto: 'vCompraTrasladoComprobantes',
                            path: 'comprobantes',
                            view: '_user/comprobantes/vComprobantes.vue',
                            permission: 'vCompraComprobantes:ver',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vCompraTrasladoComprobante',
                                    path: ':comprobante_id',
                                    view: '_user/comprobante/vComprobante.vue',
                                    permission: 'vCompraComprobantes:ver',
                                    viewType: 'detail',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        // {
        //     label: 'Recepciones detalle',
        //     goto: 'vCompraItems',
        //     path: 'recepciones-items',
        //     view: '_user/traslado_items/vTrasladoItems.vue',
        //     permisos: [
        //         { id: 'vCompraItems:listar', label: 'Listar' },
        //         { id: 'vCompraItems:inspeccion', label: 'Inspeccionar' },
        //     ],
        // },
        {
            label: 'Facturas de proveedor',
            goto: 'vCompraComprobantes',
            path: 'comprobantes',
            view: '_user/comprobantes/vComprobantes.vue',
            permisos: [
                { id: 'vCompraComprobantes:listar', label: 'Listar' },
                { id: 'vCompraComprobantes:crear', label: 'Crear' },
                { id: 'vCompraComprobantes:ver', label: 'Ver' },
                { id: 'vCompraComprobantes:editar', label: 'Editar' },
                { id: 'vCompraComprobantes:eliminar', label: 'Eliminar' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vCompraComprobante',
                    path: ':comprobante_id',
                    view: '_user/comprobante/vComprobante.vue',
                    permission: 'vCompraComprobantes:ver',
                    viewType: 'detail',
                },
            ],
        },
    ],
}
