export default {
    id: 'ventas',
    label: 'Ventas',
    icon: 'fa-solid fa-truck',
    path: 'ventas',
    children: [
        {
            label: 'Clientes',
            goto: 'vClientes',
            path: 'clientes',
            view: 'socios/vSocios.vue',
            permisos: [
                { id: 'vClientes:listar', label: 'Listar' },
                { id: 'vClientes:crear', label: 'Crear' },
                { id: 'vClientes:ver', label: 'Ver' },
                { id: 'vClientes:editar', label: 'Editar' },
                { id: 'vClientes:eliminar', label: 'Eliminar' },
                { id: 'vClientes:editarBulk', label: 'Editar masivo' },
                { id: 'vClientes:eliminarBulk', label: 'Eliminar masivo' },
            ],
        },
        {
            label: 'Pedidos',
            goto: 'vVentaPedidos',
            path: 'pedidos',
            view: '_user/socio_pedidos/vSocioPedidos.vue',
            permisos: [
                { id: 'vVentaPedidos:listar', label: 'Listar' },
                { id: 'vVentaPedidos:crear', label: 'Crear' },
                { id: 'vVentaPedidos:ver', label: 'Ver' },
                { id: 'vVentaPedidos:editar', label: 'Editar' },
                { id: 'vVentaPedidos:eliminar', label: 'Eliminar' },
                { id: 'vVentaPedidos:abrirCerrar', label: 'Abir y cerrar' },
                { id: 'vVentaPedidos:generarPdf', label: 'Generar PDF' },
                { id: 'vVentaPedidos:confirmarPago', label: 'Confirmar pago' },
                { id: 'vVentaPedidos:confirmarListo', label: 'Marcar como listo' },
                { id: 'vVentaPedidos:confirmarEntrega', label: 'Confirmar entrega' },
                { id: 'vVentaPedidos:entregarMercaderia', label: 'Entregar mercadería' },
                { id: 'vVentaPedidos:verProductosPedidos', label: 'Ver productos pedidos' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vVentaPedido',
                    path: ':pedido_id',
                    view: '_user/socio_pedido/vSocioPedido.vue',
                    permission: 'vVentaPedidos:ver',
                    viewType: 'detail',
                    children: [
                        {
                            label: 'Entregas',
                            goto: 'vVentaPedidoEntregas',
                            path: 'entregas',
                            view: '_user/traslados/vTraslados.vue',
                            permission: 'vVentaPedidos:entregarMercaderia',
                            children: [
                                {
                                    label: 'Detalle',
                                    goto: 'vVentaPedidoEntrega',
                                    path: ':traslado_id',
                                    view: '_user/traslado/vTraslado.vue',
                                    permission: 'vVentaPedidos:entregarMercaderia',
                                    viewType: 'detail',
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            label: 'Pedidos detalle',
            goto: 'vVentaPedidoItems',
            path: 'pedido-items',
            view: '_user/socio_pedido_items/vSocioPedidoItems.vue',
            permisos: [{ id: 'vVentaPedidoItems:listar', label: 'Listar' }],
        },
        {
            label: 'Despachos',
            goto: 'vVentas',
            path: 'despachos',
            view: '_user/traslados/vTraslados.vue',
            permisos: [
                { id: 'vVentas:listar', label: 'Listar' },
                { id: 'vVentas:crear', label: 'Crear' },
                { id: 'vVentas:ver', label: 'Ver' },
                { id: 'vVentas:editar', label: 'Editar' },
                { id: 'vVentas:eliminar', label: 'Eliminar' },
                { id: 'vVentas:controlDespacho', label: 'Control despacho' },
            ],
            children: [
                {
                    label: 'Detalle',
                    goto: 'vVentaTraslado',
                    path: ':traslado_id',
                    view: '_user/traslado/vTraslado.vue',
                    permission: ['vVentas:ver'],
                    viewType: 'detail',
                },
            ],
        },
        // {
        //     label: 'Despachos detalle',
        //     goto: 'vVentaItems',
        //     path: 'despachos-items',
        //     view: '_user/traslado_items/vTrasladoItems.vue',
        //     permisos: [{ id: 'vVentaItems:listar', label: 'Listar' }],
        // },
        {
            label: 'Soporte al cliente',
            goto: 'vHelpdeskTickets',
            path: 'soporte',
            view: '_user/soporte_cliente/vHelpdeskTickets.vue',
            permisos: [
                { id: 'vHelpdeskTickets:listar', label: 'Listar' },
                { id: 'vHelpdeskTickets:crear', label: 'Crear' },
                { id: 'vHelpdeskTickets:ver', label: 'Ver' },
                { id: 'vHelpdeskTickets:editar', label: 'Editar' },
                { id: 'vHelpdeskTickets:eliminar', label: 'Eliminar' },
            ],
        },
    ],
}
