export default {
    apiPath: 'transacciones',
    detailPath: 'traslado_id',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: [
                'vCompras:crear',
                'vVentas:crear',
                'vCompraPedidos:ingresarMercaderia',
                'vVentaPedidos:entregarMercaderia',
            ],
        },
        {
            text: 'Recuperar',
            action: 'recuperarGuardado',
            permiso: 'vCompras:crear',
            tipo: '2',
            showIfAvance: 'mCompra',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '8rem',
            show: true,
            orden: 1,
        },
        {
            id: 'guia',
            title: 'Guía',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'factura',
            title: 'Factura',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'socio',
            title: 'Proveedor',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '15rem',
            show: true,
            seek: true,
            orden: 4,
        },
        // {
        //     id: 'pago_condicion',
        //     title: 'Condición de pago',
        //     prop: 'pago_condicion1.nombre',
        //     type: 'select',
        //     systemKey: 'pago_condiciones',
        //     width: '12rem',
        //     show: true,
        //     orden: 5,
        // },
        // {
        //     id: 'moneda',
        //     title: 'Moneda',
        //     prop: 'moneda1.nombre',
        //     type: 'related',
        //     relatedUrl: 'monedas',
        //     width: '8rem',
        //     show: true,
        //     seek: true,
        //     orden: 6,
        // },
        // {
        //     id: 'monto',
        //     title: 'Importe',
        //     type: 'number',
        //     format: 'decimal',
        //     toRight: true,
        //     width: '8rem',
        //     show: true,
        //     orden: 7,
        // },
        // {
        //     id: 'estado',
        //     title: 'Estado',
        //     prop: 'estado1.nombre',
        //     type: 'select',
        //     systemKey: 'transaccion_estados',
        //     format: 'estado',
        //     color: 'estado1.color',
        //     width: '7rem',
        //     show: true,
        //     orden: 8,
        // },
        {
            id: 'socio_pedido',
            title: 'Nro pedido',
            prop: 'socio_pedido1.codigo',
            type: 'related',
            relatedUrl: 'socio_pedidos',
            mostrar: 'codigo',
            width: '10rem',
            show: true,
            seek: true,
            orden: 9,
        },
    ],

    tableRowActions: [
        {
            label: 'Control de despacho',
            icon: 'fa-solid fa-star',
            action: 'controlDespacho',
            permiso: 'vVentas:controlDespacho',
            ocultar: { tipo: 1 },
        },
    ],
}
