export default {
    apiPath: 'transacciones',
    detailPath: 'traslado_id',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: [
                'vCompras:crear',
                'vVentas:crear',
                'vCompraPedidos:ingresarMercaderia',
                'vVentaPedidos:entregarMercaderia',
            ],
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '8rem',
            show: true,
            orden: 1,
        },
        {
            id: 'guia',
            title: 'Guía',
            type: 'text',
            width: '12rem',
            show: true,
            seek: true,
            orden: 2,
        },
        // {
        //     id: 'factura',
        //     title: 'Factura',
        //     type: 'text',
        //     width: '8rem',
        //     show: true,
        //     seek: true,
        //     orden: 3,
        // },
        {
            id: 'socio',
            title: 'Socio comercial',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '25rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'transaccion_estados',
            format: 'estado',
            color: 'estado1.color',
            width: '8rem',
            show: true,
            orden: 8,
        },
        {
            id: 'socio_pedido',
            title: 'Nro pedido',
            prop: 'socio_pedido1.codigo',
            type: 'related',
            relatedUrl: 'socio_pedidos',
            mostrar: 'codigo',
            width: '15rem',
            show: true,
            seek: true,
            orden: 9,
        },
    ],

    tableRowActions: [
        {
            label: 'Control de despacho',
            icon: 'fa-solid fa-star',
            action: 'controlDespacho',
            permiso: 'vVentas:controlDespacho',
            ocultar: { tipo: 1 },
        },
    ],
}
