export const columns = [
    {
        id: 'nombre',
        title: 'Nombre',
        type: 'text',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'fecha_emision',
        title: 'Fecha de emisión',
        type: 'date',
        format: 'date',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'fecha_vencimiento',
        title: 'Fecha de vencimiento',
        type: 'date',
        format: 'date',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'recordar_dias',
        title: 'Recordatorio',
        type: 'number',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'estado',
        title: 'Estado',
        prop: 'estado1.nombre',
        type: 'select',
        format: 'estado',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
]

export const tableRowOptions = [
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vDocumentos:editar',
    },
    {
        label: 'Ver pdf',
        icon: 'fa-regular fa-file-pdf',
        action: 'verFile',
        permiso: 'vRegistrosSanitarios:editar',
        ocultar: { file: {} },
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'eliminar',
        permiso: 'vDocumentos:eliminar',
    },
]
