export default {
    apiPath: 'socio_pedidos',
    detailPath: 'pedido_id',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: ['vCompraPedidos:crear', 'vVentaPedidos:crear'],
        },
        {
            text: 'Recuperar',
            action: 'recuperarGuardado',
            permiso: ['vCompraPedidos:crear', 'vVentaPedidos:crear'],
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            prop: 'fecha1',
            type: 'date',
            width: '10rem',
            show: true,
            orden: 1,
        },
        {
            id: 'codigo',
            title: 'Nro pedido',
            type: 'text',
            width: '12rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'socio',
            title: 'Proveedor',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '20rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'pago_condicion',
            title: 'Condición de pago',
            prop: 'pago_condicion1.nombre',
            type: 'select',
            systemKey: 'pago_condiciones',
            width: '12rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'moneda',
            title: 'Moneda',
            prop: 'moneda1.nombre',
            type: 'related',
            relatedUrl: 'monedas',
            width: '8rem',
            show: true,
            seek: true,
            orden: 5,
        },
        {
            id: 'monto',
            title: 'Importe',
            type: 'decimal',
            format: {},
            align: 'right',
            width: '10rem',
            show: true,
            orden: 6,
        },
        {
            id: 'estado',
            title: 'Estado',
            prop: 'estado1.nombre',
            type: 'select',
            systemKey: 'pedido_estados',
            format: 'estado',
            color: 'estado1.color',
            width: '10rem',
            show: true,
            orden: 7,
        },
        {
            id: 'pagado',
            title: 'Pagado?',
            prop: 'pagado1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'estado',
            color: 'pagado1.color',
            width: '8rem',
            show: true,
            orden: 9,
        },
        {
            id: 'listo',
            title: 'Listo para entrega?',
            prop: 'listo1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'estado',
            color: 'listo1.color',
            width: '8rem',
            show: true,
            orden: 10,
        },
        {
            id: 'entregado',
            title: 'Entregado?',
            prop: 'entregado1.nombre',
            type: 'select',
            systemKey: 'estados',
            format: 'estado',
            color: 'entregado1.color',
            width: '8rem',
            show: true,
            orden: 11,
        },
        {
            id: 'origin',
            title: 'Origen',
            width: '10rem',
            type: 'text',
            show: true,
            orden: 12,
        },
        {
            id: 'createdBy',
            title: 'Creado por',
            prop: 'createdBy1.nombres',
            type: 'related',
            relatedUrl: 'colaboradores',
            mostrar: 'nombres',
            width: '10rem',
            show: true,
            seek: true,
            orden: 8,
        },
    ],

    tableRowActions: [
        {
            label: 'Abrir',
            icon: 'fa-solid fa-check-double',
            action: 'abrir',
            permiso: ['vCompraPedidos:abrir', 'vVentaPedidos:abrir'],
            ocultar: { estado: 1 },
        },
        {
            label: 'Terminar',
            icon: 'fa-solid fa-check-double',
            action: 'cerrar',
            permiso: ['vVentaPedidos:cerrar'],
            ocultar: { tipo: 1, estado: 2 },
        },
        {
            label: 'Confirmar pago',
            icon: 'fa-solid fa-hand-holding-dollar',
            action: 'confirmarPago',
            permiso: 'vVentaPedidos:confirmarPago',
            ocultar: { tipo: 1, pago_condicion: ['2', '3'], pagado: true },
        },
        {
            label: 'Marcar como listo',
            icon: 'fa-solid fa-check-double',
            action: 'confirmarListo',
            permiso: 'vVentaPedidos:confirmarListo',
            ocultar: { tipo: 1, listo: true },
        },
        {
            label: 'Confirmar entrega',
            icon: 'fa-regular fa-truck',
            action: 'confirmarEntrega',
            permiso: 'vVentaPedidos:confirmarEntrega',
            ocultar: { tipo: 1, entregado: true, listo: false },
        },
    ],
}
