export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        format: 'date',
        type: 'date',
        width: '10rem',
        show: true,
        sort: true,
    },
    {
        id: 'codigo',
        title: 'Nro pedido',
        type: 'text',
        width: '12rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'socio1.nombres',
        title: 'Proveedor',
        prop: 'socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '20rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'pago_condicion',
        title: 'Condición de pago',
        prop: 'pago_condicion1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        sort: true,
    },
    {
        id: 'moneda1.nombre',
        title: 'Moneda',
        prop: 'moneda1.nombre',
        type: 'select',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
    {
        id: 'monto',
        title: 'Importe',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '10rem',
        show: true,
        sort: true,
    },
    {
        id: 'estado',
        title: 'Estado',
        prop: 'estado1.nombre',
        type: 'select',
        format: 'estado',
        width: '10rem',
        show: true,
        sort: true,
    },
    {
        id: 'createdBy1.nombres',
        title: 'Creado por',
        prop: 'createdBy1.nombres',
        filtrable: false,
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver',
        icon: 'fa-regular fa-folder-open',
        action: 'ver',
        permiso: 'vCompraPedidos:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vCompraPedidos:editar',
        ocultar: { estado: ['0', '2'] },
    },
    {
        label: 'Eliminar',
        icon: 'fa-solid fa-trash-can',
        action: 'eliminar',
        permiso: 'vCompraPedidos:eliminar',
        ocultar: { estado: ['0', '2'] },
    },
    {
        label: 'Exportar en PDF',
        icon: 'fa-regular fa-file-pdf',
        action: 'generarPdf',
        permiso: 'vCompraPedidos:generarPdf',
    },
    {
        label: 'Terminar',
        icon: 'fa-solid fa-check-double',
        action: 'terminar',
        permiso: 'vCompraPedidos:terminar',
        ocultar: { estado: ['0', '2'] },
    },
    {
        label: 'Recalcular entregados',
        icon: 'fa-solid fa-calculator',
        action: 'recalcularEntregados',
        permiso: 'vCompraPedidos:recalcularEntregados',
        ocultar: { estado: ['0', '2'] },
    },
    {
        label: 'Entregar mercadería',
        icon: 'fa-regular fa-circle-down',
        action: 'entregarMercaderia',
        permiso: 'vCompraPedidos:entregarMercaderia',
        ocultar: { estado: ['0', '2'], is_maquila: false },
    },
    {
        label: 'Ingresar mercadería',
        icon: 'fa-regular fa-circle-up',
        action: 'ingresarMercaderia',
        permiso: 'vCompraPedidos:ingresarMercaderia',
        ocultar: { estado: ['0', '2'] },
    },
]
