export const HEADER_ACTIONS = [
    {
        text: 'Nuevo',
        action: 'nuevo',
        permiso: 'vCompras:crear',
    },
    {
        text: 'Recuperar',
        action: 'recuperarGuardado',
        permiso: 'vCompras:crear',
        tipo: '2',
        showIfAvance: 'mCompra',
    },
]

export const TABLE_COLUMNS = [
    {
        id: 'fecha',
        title: 'Fecha',
        type: 'date',
        format: 'date',
        width: '8rem',
        show: true,
        sort: true,
        orden: 1,
    },
    {
        id: 'guia',
        title: 'Guía',
        type: 'text',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
        orden: 2,
    },
    {
        id: 'factura',
        title: 'Factura',
        type: 'text',
        width: '8rem',
        show: true,
        seek: true,
        sort: true,
        orden: 3,
    },
    {
        id: 'socio1.nombres',
        title: 'Proveedor',
        prop: 'socio1.nombres',
        type: 'select',
        mostrar: 'nombres',
        width: '15rem',
        show: true,
        seek: true,
        sort: true,
        orden: 4,
    },
    {
        id: 'pago_condicion',
        title: 'Condición de pago',
        prop: 'pago_condicion1.nombre',
        type: 'select',
        width: '12rem',
        show: true,
        sort: true,
        orden: 5,
    },
    {
        id: 'moneda',
        title: 'Moneda',
        prop: 'moneda1.nombre',
        type: 'select',
        width: '8rem',
        show: true,
        sort: true,
        orden: 6,
    },
    {
        id: 'monto',
        title: 'Importe',
        type: 'number',
        format: 'decimal',
        toRight: true,
        width: '8rem',
        show: true,
        sort: true,
        orden: 7,
    },
    {
        id: 'estado',
        title: 'Estado',
        type: 'select',
        prop: 'estado1.nombre',
        format: 'estado',
        width: '7rem',
        show: true,
        sort: true,
        orden: 8,
    },
    {
        id: 'socio_pedido1.codigo',
        title: 'Pedido',
        filtrable: false,
        prop: 'socio_pedido1.codigo',
        width: '10rem',
        show: true,
        seek: true,
        sort: true,
        orden: 9,
    },
]

export const TABLE_ROW_ACTIONS = [
    {
        label: 'Ver',
        icon: 'fa-regular fa-folder-open',
        action: 'ver',
        permiso: 'vCompras:ver',
    },
    {
        label: 'Editar',
        icon: 'fa-solid fa-pen-to-square',
        action: 'editar',
        permiso: 'vCompras:editar',
        ocultar: { estado: 2 },
    },
]
