export default {
    name: 'vVentas',
    title: 'Ventas',
    apiPath: 'transacciones',

    headerActions: [
        {
            text: 'Nuevo',
            action: 'nuevo',
            permiso: 'vVentas:crear',
        },
        {
            text: 'Recuperar',
            action: 'recuperarGuardado',
            permiso: 'vVentas:crear',
            tipo: '2',
            showIfAvance: 'mVenta',
        },
        {
            icon: 'fa-solid fa-download',
            text: 'Exportar página actual',
            action: 'vista.downloadActualTablePage',
            tipo: '2',
        },
    ],

    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            type: 'date',
            format: 'date',
            width: '10rem',
            show: true,
            sort: true,
            orden: 1,
        },
        {
            id: 'guia',
            title: 'Guía',
            type: 'text',
            width: '10rem',
            show: true,
            seek: true,
            sort: true,
            orden: 2,
        },
        {
            id: 'socio1.nombres',
            title: 'Cliente',
            prop: 'socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            width: '20rem',
            show: true,
            seek: true,
            sort: true,
            orden: 3,
        },
        {
            id: 'pago_condicion',
            title: 'Condición de pago',
            prop: 'pago_condicion1.nombre',
            type: 'related',
            systemKey: 'pago_condiciones',
            width: '12rem',
            show: true,
            sort: true,
            orden: 4,
        },
        {
            id: 'moneda',
            title: 'Moneda',
            prop: 'moneda1.nombre',
            type: 'related',
            relatedUrl: 'monedas',
            width: '8rem',
            show: true,
            sort: true,
            orden: 5,
        },
        {
            id: 'monto',
            title: 'Importe',
            type: 'number',
            format: 'decimal',
            toRight: true,
            width: '8rem',
            show: true,
            sort: true,
            orden: 6,
        },
        {
            id: 'estado',
            title: 'Estado',
            type: 'related',
            systemKey: 'transaccion_estados',
            prop: 'estado1.nombre',
            format: 'estado',
            width: '7rem',
            show: true,
            sort: true,
            orden: 7,
        },
    ],

    tableRowActions: [
        {
            label: 'Ver',
            icon: 'fa-regular fa-folder-open',
            action: 'ver',
            permiso: 'vVentas:ver',
        },
        {
            label: 'Editar',
            icon: 'fa-solid fa-pen-to-square',
            action: 'editar',
            permiso: 'vVentas:editar',
            ocultar: { estado: 2 },
        },
        {
            label: 'Control de despacho',
            icon: 'fa-solid fa-star',
            action: 'controlDespacho',
            permiso: 'vVentas:controlDespacho',
        },
    ],
}

