export default {
    name: 'vCompraItems',
    title: 'Artículos comprados',
    apiPath: 'transaccion_items',

    headerActions: [],

    tableColumns: [
        {
            id: 'transaccion1.fecha',
            title: 'Fecha',
            prop: 'transaccion1.fecha1',
            type: 'date',
            width: '8rem',
            show: true,
            orden: 1,
        },
        {
            id: 'transaccion1.guia',
            title: 'Guía',
            type: 'text',
            prop: 'transaccion1.guia',
            width: '8rem',
            show: true,
            seek: true,
            orden: 2,
        },
        {
            id: 'transaccion1.factura',
            title: 'Factura',
            type: 'text',
            prop: 'transaccion1.factura',
            width: '8rem',
            show: true,
            seek: true,
            orden: 3,
        },
        {
            id: 'transaccion1.socio',
            title: 'Proveedor',
            prop: 'transaccion1.socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '15rem',
            show: true,
            seek: true,
            orden: 4,
        },
        {
            id: 'articulo',
            title: 'Artículo',
            prop: 'articulo1.nombre',
            type: 'related',
            relatedUrl: 'articulos',
            width: '20rem',
            show: true,
            seek: true,
            orden: 5,
        },
        {
            id: 'cantidad',
            title: 'Cantidad',
            type: 'decimal',
            format: {},
            align: 'right',
            width: '8rem',
            show: true,
            orden: 6,
        },
        {
            id: 'transaccion1.socio_pedido1.codigo',
            title: 'Nro pedido',
            prop: 'transaccion1.socio_pedido1.codigo',
            type: 'text',
            width: '12rem',
            show: true,

            orden: 10,
        },
    ],
}
