export default {
    name: 'vKardex',
    title: 'Kardex',
    apiPath: 'kardex',
    headerActions: [],
    tableColumns: [
        {
            id: 'fecha',
            title: 'Fecha',
            type: 'date',
            prop: 'fecha1',
            width: '8rem',
            show: true,
        },
        {
            id: 'tipo',
            title: 'Operación',
            prop: 'tipo1.nombre',
            width: '15rem',
            show: true,
            filtrable: false,
        },
        {
            id: 'articulo',
            title: 'Artículo',
            prop: 'articulo1.nombre',
            type: 'related',
            relatedUrl: 'articulos',
            width: '20rem',
            show: true,
            seek: true,
        },
        {
            id: 'lote',
            title: 'Lote',
            prop: 'lote1.codigo',
            type: 'related',
            relatedUrl: 'lotes',
            width: '8rem',
            show: true,
            seek: true,
        },
        {
            id: 'lote1.fv',
            title: 'Fecha vencimiento',
            prop: 'lote1.fv1',
            width: '8rem',
            show: true,
        },
        {
            id: 'lote1.vu',
            title: 'Valor unitario',
            toRight: true,
            type: 'number',
            width: '8rem',
            show: true,
        },
        // {
        //     id: 'lote1.pu',
        //     title: 'Precio unitario',
        //     toRight: true,
        //     filtrable: false,
        //     width: '8rem',
        //     show: true,
        // },
        {
            id: 'cantidad',
            title: 'Cantidad',
            prop: 'cantidad1',
            format: 'decimal',
            toRight: true,
            type: 'number',
            width: '8rem',
            show: true,
        },
        {
            id: 'maquina',
            title: 'Máquina',
            prop: 'maquina1.nombre',
            type: 'related',
            relatedUrl: 'maquinas',
            width: '10rem',
            show: true,
            seek: true,
        },
        {
            id: 'transaccion1.socio',
            title: 'Socio comercial',
            prop: 'transaccion1.socio1.nombres',
            type: 'related',
            relatedUrl: 'socios',
            mostrar: 'nombres',
            width: '15rem',
            show: true,
            seek: true,
        },
        {
            id: 'transaccion1.guia',
            title: 'Guía',
            prop: 'transaccion1.guia',
            width: '8rem',
            show: true,
            seek: true,
        },
        {
            id: 'observacion',
            title: 'Observación',
            type: 'text',
            width: '8rem',
            show: true,
            seek: true,
        },
    ],
    tableRowActions: [
        {
            label: 'Ver compra',
            icon: 'fa-regular fa-folder-open',
            action: 'verCompra',
            ocultar: { tipo: { op: '!=', val: 1 } },
        },
        {
            label: 'Ver venta',
            icon: 'fa-regular fa-folder-open',
            action: 'verCompra',
            ocultar: { tipo: { op: '!=', val: 5 } },
        },
    ],
}
