export default {
    apiPath: 'produccion_ordenes',
    titleKey: 'fecha1',
    pathKey: 'produccion_orden_id',
    permisoEditar: ['vProduccionOrdenes:editar', 'vProduccionOrdenes:editar'],
    permisoClonar: ['vProduccionOrdenes:clonar', 'vProduccionOrdenes:clonar'],

    headerActions: [
        {
            text: 'Inicar',
            icon: 'fa-solid fa-play',
            tipo: '2',
            action: 'iniciar',
            permiso: 'vProduccionOrdenes:iniciarTerminar',
            ocultar: { estado: 2, inicio: { op: '!=', val: null } },
        },
        {
            text: 'Terminar',
            icon: 'fa-solid fa-stop',
            tipo: '2',
            action: 'terminar',
            permiso: 'vProduccionOrdenes:iniciarTerminar',
            ocultar: { estado: 2, inicio: { op: '=', val: null }, fin: { op: '!=', val: null } },
        },
        {
            text: 'Abrir',
            icon: 'fa-solid fa-check-double',
            tipo: '2',
            action: 'abrir',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 1 },
        },
        {
            text: 'Cerrar',
            icon: 'fa-solid fa-check-double',
            tipo: '2',
            action: 'cerrar',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 2 },
        },
        {
            text: 'Formatos de calidad',
            icon: 'fa-regular fa-file',
            tipo: '2',
            action: 'openFormatos',
            permiso: 'vProduccionOrdenes:abrirCerrar',
            ocultar: { estado: 2 },
        },
    ],
}
